@path = api/v1/users
@username = test
@email = test@test.com.br
@password = test_123

# Registra um novo usuário no sistema
POST {{host}}/{{path}}
Content-Type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "password": "{{password}}"
}